import { Clock, Timer, UserCheck, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Card, CardHeader, EmptyState, PageHeader, StatCard } from '../components/ui'
import { api, formatDuration } from '../lib/api'

export default function AnalyticsPage() {
  const [days, setDays] = useState(7); const [data, setData] = useState(null)
  useEffect(() => { api(`/api/analytics/overview?days=${days}`).then(setData).catch(() => {}) }, [days])
  return <><PageHeader eyebrow="Insights" title="Presence analytics" description="Metrics are calculated from persisted sessions, never browser state." actions={<div className="segmented">{[[1, 'Today'], [7, '7 days'], [30, '30 days']].map(([value, label]) => <button key={value} className={days === value ? 'active' : ''} onClick={() => setDays(value)}>{label}</button>)}</div>}/><div className="stat-grid"><StatCard label="Unique people" value={data?.uniquePeople ?? '—'} detail={`Last ${days} day${days > 1 ? 's' : ''}`} icon={UserCheck} tone="blue"/><StatCard label="Total visits" value={data?.totalVisits ?? '—'} detail={`${data?.unknownVisits || 0} unknown`} icon={Users} tone="green"/><StatCard label="Total presence" value={data ? formatDuration(data.totalPresenceSeconds) : '—'} detail="Closed sessions" icon={Clock} tone="violet"/><StatCard label="Average visit" value={data ? formatDuration(data.averageVisitSeconds) : '—'} detail="Closed sessions" icon={Timer} tone="amber"/></div><div className="two-charts"><Card><CardHeader title="Daily visits" subtitle="Visit volume by date"/>{data?.daily?.length ? <div className="chart"><ResponsiveContainer><AreaChart data={data.daily}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#202d42"/><XAxis dataKey="day" tick={{fill:'#75839a',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'#75839a',fontSize:11}}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #27354b',borderRadius:10}}/><Area dataKey="visits" stroke="#55d99a" fill="rgba(85,217,154,.12)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div> : <EmptyState/>}</Card><Card><CardHeader title="Entry distribution" subtitle="Entries by hour"/>{data?.hourly?.length ? <div className="chart"><ResponsiveContainer><BarChart data={data.hourly}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#202d42"/><XAxis dataKey="hour" tick={{fill:'#75839a',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'#75839a',fontSize:11}}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #27354b',borderRadius:10}}/><Bar dataKey="entries" fill="#668cff" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div> : <EmptyState/>}</Card></div></>
}
